### ISSUE TITLE
gpg: keyserver receive failed: No name

### ISSUE THREAD

**Issue by ghost** [ngmy/phive-install-action#16]
Hi, 

on executing `gpg --keyserver pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79` I get an _gpg: keyserver receive failed: No name_ and my pipeline fails.

A currently woking keyserver is: _hkps://keyserver.ubuntu.com_.

Could you fix this? Or am I missing something?

Regards! Wolfram

**Comment by ngmy** [comment]
Please wait for #17 to be fixed and merged.

**Comment by ngmy** [comment]
Fixed in #17.

**Comment by ghost** [comment]
Merci!
